//
//  MenuViewController.swift
//  iVictim
//
//  Created by Azzaro Mujic on 31/05/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol MenuViewControllerOutput {
    func presentBadLogIn()
    func presentLocalStorage()
    func presentBruteForce()
    func presentSSLPinning()
}

final class MenuViewController: UIViewController {
    
    var output: MenuViewControllerOutput!
    
    // MARK: - View lifecycle -
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
    }
  
    // MARK: - Public functions -

    // MARK: - IBActions -
  
    // MARK: - Private functions -
}


extension MenuViewController: UITableViewDataSource, UITableViewDelegate {
    
    func numberOfSectionsInTableView(tableView: UITableView) -> Int {
        return 1
    }
    
    func tableView(tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return MenuItem.items.count
    }
    
    func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCellWithIdentifier("BasicCell")!
        cell.textLabel?.text = MenuItem.items[indexPath.row].rawValue
        
        return cell
    }
    
    func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {
        switch MenuItem.items[indexPath.row] {
        case .BadLogin:
            output.presentBadLogIn()
        case .LocalStorage:
            output.presentLocalStorage()
        case .BruteForce:
            output.presentBruteForce()
        case .SSLPinning:
            output.presentSSLPinning()
        }
        
    }
}

enum MenuItem: String {
    case BadLogin
    case LocalStorage = "Local Storage"
    case BruteForce = "Brute Force"
    case SSLPinning = "SSL Pinning"
    
    static var items: [MenuItem] {
        return [MenuItem.BadLogin, MenuItem.LocalStorage, MenuItem.BruteForce, MenuItem.SSLPinning]
    }
}