//
//  HomeViewController.swift
//  iVictim
//
//  Created by Azzaro Mujic on 31/05/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

// MARK: -  Home View Controller -
protocol HomeViewControllerOutput: class {
    
}

final class HomeViewController: UIViewController {
    
    var output: HomeViewControllerOutput!
    
    // MARK: - Home view interface requirements
    
    weak var menuViewController: MenuViewController?
    @IBOutlet weak var menuBackgroundVuew: UIView!
    @IBOutlet weak var menuParentView: UIView!
    
    // MARK: - View lifecycle -
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.menuBackgroundVuew.alpha = 0
        self.menuParentView.transform = CGAffineTransformMakeTranslation(-screenWidth(), 0)
    }
    
    override func viewWillAppear(animated: Bool) {
        super.viewWillAppear(animated)
        navigationController?.setNavigationBarHidden(true, animated: animated)
    }
  
    // MARK: - Public functions -

    // MARK: - IBActions -
  
    @IBAction func menuBackButtonClicked(sender: AnyObject) {
        _hideMenu()
    }
    @IBAction func menuButtonClicked(sender: UIButton) {
        _showMenu()
    }
    // MARK: - Private functions -
    
    func _showMenu() {
        UIView.animateWithDuration(0.2) { 
            self.menuBackgroundVuew.alpha = 1
            self.menuParentView.transform = CGAffineTransformIdentity
        }
    }
    
    func _hideMenu() {
        UIView.animateWithDuration(0.2) {
            self.menuBackgroundVuew.alpha = 0
            self.menuParentView.transform = CGAffineTransformMakeTranslation(-screenWidth(), 0)
        }
    }
    
    override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?) {
        if segue.identifier == MenuViewController.storyboardIdentifier {
            menuViewController = segue.destinationViewController as? MenuViewController
        }
    }
}
